const text = "Apresentamos os Termos de Uso do domínio digital Neopag.Sugerimos, também, a leitura atenta de nossa Política de Privacidade, também disponível nessa mesma página." +
    "Apresentamos os Termos de Uso da plataforma digital de private label – Neopag." +
    "Sugerimos, também, a leitura atenta de nossa Política de Privacidade, facilmente localizada através desse link: https://www.neopag.com/politica-de-privacidade. Para melhor organizar as informações, arrolamos, na sequência, os principais pontos deste Termo de Uso, mas destacamos ser muito importante a leitura da integralidade desse documento:" +
    "Todo o relacionamento e interação dos Usuários com a plataforma Neopag é realizada de forma digital e online." +
    "O Usuário não pagará qualquer tarifa pela a utilização da plataforma Neopag.Para utilizar a plataforma Neopag o Usuário baixa o aplicativo na loja virtual do seu smartphone, informa o número do seu CPF, e cria uma senha pessoal, sigilosa e intransferível.O Usuário não deve, em hipótese alguma, divulgar essa senha para terceiros e é o único responsável pelo uso não autorizado da senha cadastrada." +
    "O cadastro deverá ser efetivado completamente, facultando ao Usuário, ao depois do envio da documentação necessária, selecionar a loja conveniada de sua preferência e requerer crédito para a realização de suas compras, ocasião em que será digitalmente apresentado ao Usuário o Contrato de Emissão e Utilização de Cartão Private Label Digital Neopag a ser efetivado com a loja conveniada, definidor dos direitos, deveres e responsabilidades das partes negociantes.Requerido o crédito e aposto, ao depois da leitura integral, o aceite aos termos do Contrato de Emissão e Utilização de Cartão Private Label Digital Neopag (contratação “click-wrap”) com a loja conveniada, a equipe especializada da Neopag passará a analisar internamente os dados do Usuário, e, em tempo breve, acusará na própria plataforma/aplicativo do Usuário o avalor do crédito concedido, calculado através de critérios objetivos, incluindo consulta em órgãos de proteção ao crédito.A recusa na concessão do crédito após a verificação dos dados objetivos pesquisados não constitui qualquer medida discriminatória ou de índole pessoal, não implicando, por essa razão, em qualquer espécie de responsabilidade à Neopag.Como medida de maior segurança para o Usuário, além da senha pessoal a ser cadastrada, para a confirmação de todas as transações realizadas através da plataforma Neopag será gerado um token pelo sistema, a ser informado à loja para a efetivação da compra." +
    "Todas as informações dos Usuários são sigilosas e confidenciais, podendo ser utilizadas apenas e tão somente para a finalidade da plataforma Neopag, sendo autorizado, com a aceitação desses Termos, o acesso dessas informações pelas lojas conveniadas à plataforma Neopag.A utilização da plataforma Neopag é permitida apenas aos Usuários que possuem capacidade civil plena para a celebração de negócio jurídico, ou seja, maiores de 18 anos de idade.Ao utilizar a plataforma Neopag, o Usuário pode ter acesso também a serviços de terceiros.Nesse caso, os Usuários deverão analisar cuidadosamente os Termos de Uso desses terceiros.A Neopag não é responsável por esses serviços de terceiros." +
    "1.PRIMEIRAS INFORMAÇÕES" +
    "Ficamos gratos por utilizar nossa plataforma de private label digital desenvolvida pela NEOPAG SERVIÇOS DE GESTÃO DE CRÉDITO E PARTICIPAÇÕES S.A., pessoa jurídica de direito privado, com sede na cidade de São Paulo/Capital, na Rua Maria Curupaiti, n0 441, sala 7001, Torre Design, Bairro Vila Ester, CEP 02452-001, inscrita no CNPJ sob o no 29.118.949/0001-72.Ao baixar nosso aplicativo e utilizar, de qualquer forma, nossos serviços, você estará concordando com esses Termos de Uso.Seu acordo conosco inclui esses Termos de Uso e nossa Política de Privacidade disponibilizada em https://www.neopag.com/politica-de-privacidade, sendo que ao utilizar nossos Serviços, você confirma que leu, compreendeu e está de acordo com os termos previstos, comprometendo-se a cumpri-los de forma integral.A aceitação desses Termos de Uso não supre, para a efetiva concessão de crédito e consumação de compra em crediário, a necessidade de firmar eletronicamente, o Contrato de Emissão e Utilização de Cartão Private Label Digital Neopag com a loja conveniada a que o Usuário requereu crédito, o qual será disponibilizado na plataforma Neopag para leitura e aceitação de forma simples e rápida Para fazer uso da plataforma Neopag o Usuário precisa, concomitantemente: (i) ter 18 (dezoito) anos de idade ou mais; (ii) ter um RG ou CNH em mãos; (iii) ter a capacidade de celebrar um contrato vinculativo e não ser impedido de fazê-lo segundo as leis aplicáveis; (iv) ser residente no Brasil, onde os Serviços estão disponíveis; e (v) ter um smartphone com sistema operacional IOS ou Android, nas versões mínimas, com câmera frontal e com acesso à internet banda larga (3G ou 4G). O Usuário também confirma que quaisquer informações de cadastro enviadas são verdadeiras, precisas e completas, tendo ciência que qualquer incompatibilidade apurada ocasionará a impossibilidade de uso da plataforma/aplicativo, sem qualquer responsabilidade da Neopag." +
    "2. DEFINICÕES" +
    "Para os fins destes Termos e Condições de Uso, as designações abaixo terão  os seguintes significados: Usuário(s): a pessoa física, maior de idade, ou jurídica, por intermédio de representante legal devidamente habilitado, com plena capacidade de contratar, que acessa a plataforma Neopag e realiza o seu cadastro pessoal de modo a usufruir das funcionalidades oferecidas pela plataforma/aplicativo Neopag, aceitando, nessa oportunidade, incondicionalmente, os presentes Termos de Uso e a Política de Privacidade.Plataforma ou Plataforma/Aplicativo Neopag: o aplicativo da Neopag desenvolvido para operação em smartphone que tenha o sistema operacional IOS ou Android, nas versões mínimas, com camera frontal e com acesso à internet banda larga (3G ou 4G).Neopag: é a sociedade empresária NEOPAG SERVIÇOS DE GESTÃO DE CRÉDITO E PARTICIPAÇÕES S.A., pessoa jurídica de direito privado, com sede na cidade de São Paulo/Capital, na Rua Maria Curupaiti, n0 441, sala 7001, Torre Design, Bairro Vila Ester, CEP 02452-001, inscrita no CNPJ sob o no 29.118.949/0001-72.Loja Conveniada: Comércio varejista que aderiu ao sistema Neopag de gerenciamento de seu crédito e por essa razão realiza vendas no crediário através da plataforma Neopag, relação essa regida por contrato específico firmado entre a loja e a Neopag.Dados Pessoais: significa todo e qualquer dado disponibilizado pelo Usuário que, de alguma forma, o identifique, como, exemplificativamente, nome, endereço, CPF, número de telefone, endereço de e-mail, ou quaisquer outras informações.Serviço(s): Todos os serviços postos à disposição do Usuário na plataforma Neopag.SAC: Serviço de atendimento ao Usuário/Cliente da plataforma Neopag, que poderá ser consultado através do e-mail: meajuda @neopag.com.Termos de Uso: Os presentes Termos aplicáveis a todas as compras feitas através da plataforma private label digital Neopag.Política de Privacidade: significa a política de privacidade que disciplina a utilização dos dados do Usuário, que pode ser encontrada no seguinte link: https://www.neopag.com/politica-de-privacidade.Aceitar ou Aceite: o ato de o Usuário clicar na caixa “Li e aceito os Termos de Uso e Política de Privacidade”, bem assim, na caixa “Li e aceito os termos do Contrato de Emissão e Utilização de Cartão Private Label Digital Neopag” dispostas na plataforma/aplicativo Neopag. Tal ato implica consentimento prévio, expresso e informado do Usuário em relação a todo o disposto em tais documentos, autorizando o armazenamento de base de dados composta por Dados Pessoais, entre outras informações." +
    "3. ENTENDENDO A PLATAFORMA NEOPAG – VEJA OS BENEFÍCIOS!Neopag é a primeira plataforma gestão de crédito e fidelização de clientes do Brasil.Ela permite que lojistas ofereçam seu próprio CARTÃO DIGITAL apoiado por um conjunto de ferramentas para gestão de risco, crédito, relacionamento e cobrança.Neopag é vender mais, com seguraça e tranquilidade.Quais vantagens, como consumidor (Usuário), eu tenho com Neopag?Neopag ajuda você conseguir crédito para comprar nas suas lojas preferidas.Com o aplicativo Neopag voce controla todos os CARTÕES DIGITAIS, organiza suas compras, controla suas faturas e usando o aplicativo você ganha pontos pra conseguir descontos, promoções exclusivas e mais crédito para continuar comprando.Como funciona?Primeiro você precisa baixar o aplicativo e se cadastrar.Fique tranquilo, o processo é 100% seguro e sigiloso.Após o cadastro você terá acesso à lista de lojas da sua região que usam Neopag.Encontrando a sua loja preferida basta conectar com ela.Como consigo crédio?Quando você se conecta com uma loja, acontece um processo de avaliação de crédito que vai definir o quanto você conseguirá comprar na loja.Você conseguirá ver tudo no aplicativo.Não se preocupe se não conseguir crédito, a Neopag ajuda você a completar informações para ganhar mais pontos.Posso comprar em qualquer loja?A Neopag fortalece o vinculo entre lojistas e seus clientes, além de construir uma rede de confiança para conectar novos lojistas e novos clientes para fortalecer a economia local.Desta forma todas as lojas credenciadas na plataforma Neopag estarão disponiveis para que você se conecte e eventualmente consiga crédito para compras.Como faço para comprar?Basta ir até qualquer loja da rede Neopag e informar que quer comprar com Neopag.O processo é bem simples, você escolhe seus produtos e no momento de pagar você informa quantas vezes quer parcelar suas compras e confirma a compra.Como faço para pagar?Você poderá acompanhar as faturas e os valores a pagar em cada uma das lojas.O pagamento é feito diretamente na loja ou outra forma de pagamento que ela disponibilizar." +
    "4. ADESÃO, CIÊNCIA DO NEGÓCIO JURÍDICO REALIZADO E CONSEQUÊNCIAS DO INADIMPLEMENTO" +
    "‍Para obtenção da totalidade dos benefícios proporcionados pela plataforma Neopag, o Usuário deverá efetuar o seu cadastro na plataforma/aplicativo Neopag, fornecendo seus Dados Pessoais.Para a realização do cadastro, é obrigatória a leitura, compreensão e Aceite dos presentes Termos de Uso e da Política de Privacidade pelo Usuário.Para a obtenção de crédito para utilização na loja conveniada o Usuário deverá ler e aceitar os termos do Contrato de Emissão e Utilização de Cartão Private Label Digital Neopag firmado com o comerciante.O ACEITE DOS TERMOS DE USO, DA POLÍTICA DE PRIVACIDADE E DO CONTRATO DE EMISSÃO E UTILIZAÇÃO DE CARTÃO PRIVATE LABEL DIGITAL NEOPAG IRÁ IMPLICAR O RECONHECIMENTO, PELO USUÁRIO, DE QUE ELE LEU, ENTENDEU E ACEITOU INCONDICIONALMENTE TODAS AS DISPOSIÇÕES CONSTANTES DESSES DOCUMENTOS, ADMITINDO QUE AS COMPRAS REALIZADAS ATRAVÉS DA PLATAFORMA NEOPAG SÃO DE SUA RESPONSABILIDADE, ESTANDO SUJEITO AOS MEIOS DE CONBRANÇA EXTRAJUDICIAIS E JUDICIAIS EM CASO DE INADIMPLEMENTO." +
    "5. DA UTILIZAÇÃO DA PLATAFORMA NEOPAG" +
    "5.1.A Neopag, por meio deste Termos de Uso, concede ao Usuário uma licença pessoal, limitada, temporária, mundial, revogável, não exclusiva e intransferível de uso da plataforma/aplicativo, sem cobrança de remuneração do Usuário de qualquer natureza, sendo certo que o Usuário não poderá utilizar e nem permitir o uso da plataforma para qualquer outra finalidade não expressamente prevista neste Termos de Uso.Desta forma, não será permitido ao Usuário, sem qualquer limitação, copiar, modificar, distribuir, vender, alugar, compartilhar ou, ainda, ceder, a qualquer título, os serviços disponibilizados pela Neopag." +
    "‍5.2.No ato de seu cadastro na plataforma Neopag, o Usuário fornecerá à Neopag seus Dados Pessoais, criando uma senha confidencial e de responsabilidade exclusiva do Usuário." +
    "‍5.2.1.O Usuário será responsável pela veracidade, validade e precisão dos Dados Pessoais por ele fornecidos no seu cadastro, competindo-lhe manter referido cadastro sempre atualizado." +
//  ‍"5.2.2.A Neopag não terá obrigação de policiar ou fiscalizar os Dados Pessoais fornecidos pelos Usuários, mas poderá, a seu exclusivo critério, excluir as informações que lhe pareçam inverídicas ou excessivas." +
// ‍ "5.3.A utilização da plataforma pelo Usuário possui caráter pessoal e intransferível e está autorizada unicamente para fins lícitos relacionados ao propósito a que a plataforma/aplicativo se destina, de acordo com estes Termos de Uso.A propriedade intelectual da plataforma pertence, e continuará pertencendo, exclusivamente à Neopag.‍" +
    "6. DA COMUNICAÇÃO COM A NEOPAG" +
// ‍"Para qualquer assunto relacionado às condições destes Termos de Uso ou da Política de Privacidade, bem como ao Contrato de Emissão e Utilização de Cartão Private Label Digital Neopag e à plataforma/aplicativo, o Usuário deverá entrar em contato com a Neopag mediante mensagem endereçada ao e- mail meajuda @neopag.com ou através do watts up pelo n.11 94058-4887." +
    "7. PROPRIEDADE INTELECTUAL" +
    "7.1.O Usuário não adquire, por meio do presente Termos de Uso ou da Política de Privacidade, nenhum direito de propriedade intelectual ou outros direitos exclusivos, incluindo patentes, desenhos, marcas, direitos autorais ou direitos sobre informações confidenciais ou segredos de negócio, sobre ou relacionados ao Aplicativo, bem como à base de dados composta por dados de Usuários, os quais são de propriedade exclusiva da Neopag." +
// ‍"7.2.Todo e qualquer conteúdo disponibilizado na plataforma/aplicativo, bem como toda e qualquer base de dados constituída pela Neopag pertencem exclusivamente à Neopag e são protegidos pela lei brasileira, especialmente no que se refere à propriedade intelectual e aos direitos autorais.Na qualidade de exclusivo titular da propriedade intelectual da citada base de dados, a Neopag poderá utilizá-la livremente e da forma que melhor atenda seus interesses." +
// ‍"7.3.A Neopag poderá, a seu exclusivo critério, a qualquer tempo e sem necessidade de comunicação prévia ao Usuário: (i) encerrar, modificar ou suspender, total ou parcialmente, o acesso do Usuário à plataforma/aplicativo, quando referido acesso ou cadastro violar as condições estabelecidas nestes Termos de Uso e/ou na Política de Privacidade; (ii) excluir, total ou parcialmente, as informações cadastradas pelo Usuário que não estejam em consonância com as disposições destes Termos de Uso;" +
// ‍"7.4.Poderá, ainda, a Neopag, a seu exclusivo critério, suspender, modificar ou encerrar as atividades da plataforma, mediante comunicação prévia ao Usuário, salvo nas hipóteses de ato de autoridade competente, caso fortuito ou força maior." +
// ‍"7.5.A Neopag poderá, a qualquer tempo, mediante comunicação prévia ao Usuário no endereço de e-mail por este indicado em seu cadastro pessoal e por meio de aviso na própria plataforma Neopag, definir preços para oferecimento de determinados Conteúdos e/ou Serviços, ainda que inicialmente tenham sido ofertados de forma gratuita e deverá, ainda, de forma clara, indicar qual o preço vigente de determinado serviço, questionando o Usuário sobre a sua vontade de prosseguir com referida contratação." +
// ‍"7.6.O Usuário AUTORIZA, neste ato, a Neopag a enviar para o seu endereço de e-mail mensagens ou outras correspondências de caráter informativo, comercial e/ou promocional.‍" +
    "8. INFORMAÇÕES CONFIDENCIAIS E POLÍTICA DE PRIVACIDADE" +
    "8.1.Ao cadastrar-se na plataforma Neopag, o Usuário concorda com a Política de Privacidade: https://www.neopag.com/politica-de-privacidade. Mediante Aceite da Política de Privacidade, o Usuário concede à Neopag AUTORIZAÇÃO para uso dos seus dados, de acordo com as regras constantes destes Termos de Uso e da Política de Privacidade." +
    "8.2.Ao emitir o seu “de acordo” no momento do cadastro, o Usuário autoriza que a Neopag divulgue, compartilhe e troque as suas informações com qualquer outro terceiro, para fins de registro, análise de risco de crédito e qualquer outra finalidade." +
    "8.3.O Usuário autoriza a Neopag a verificar os dados fornecidos no cadastro e a obter e fornecer tais informações às empresas de análises de crédito e de proteção ao crédito e ao Sistema de Informações de Crédito (“SCR”) do Banco Central do Brasil, inclusive informações decorrentes de operações de crédito de sua responsabilidade, para fins de avaliação do risco de crédito e intercâmbio de informações com outras instituições financeiras.O Usuário declara estar ciente de que a consulta ao SCR depende dessa prévia autorização e que o Usuário pode ter acesso aos dados do SCR pelos meios colocados à sua disposição pelo Banco Central do Brasil.Em caso de divergência nos dados do SCR fornecidos pela Neopag, o Usuário poderá solicitar correção, exclusão ou registro de anotação complementar, mediante solicitação formal.O Usuário declara estar ciente de que, ocorrendo a falta de pagamento de qualquer obrigação assumida e não sendo solucionada a pendência pela via extrajudicial, será promovida demanda judicial competente." +
    "9. INDENIZAÇÃO" +
    "9.1.O Usuário concorda em defender, indenizar e manter indene a Neopag, diretores, empregados e agentes, de e contra quaisquer encargos, ações ou demandas, incluindo, exemplificativamente, honorários advocatícios razoáveis, resultantes: (i) da eventual utilização indevida da plataforma Neopag; (ii) da violação das condições ora pactuadas; (iii) qualquer atividade da qual o Usuário participe ou por meio dos Serviços; e (iv) a violação de qualquer lei ou dos direitos de terceiro." +
    "‍9.2.Em nenhum caso a Neopag será responsável por danos pessoais ou qualquer prejuízo incidental, direto, indireto ou consequente, lucros cessantes, incluindo, sem limitação, prejuízos por lucros cessantes, corrupção ou perda de dados, falha de transmissão ou recepção de dados, não continuidade do negócio ou qualquer outro prejuízo ou perda comercial, decorrentes ou relacionados à prestação de serviços por terceiros." +
    "10. VIGÊNCIA E RESCISÃO" +
    "10.1.Estes Termos de Uso e a Política de Privacidade vigerão por prazo indeterminado, a partir do Aceite do Usuário, podendo ser modificados ou rescindidos unilateralmente por qualquer das partes a qualquer tempo, sem qualquer ônus, mediante simples comunicação por meio da própria plataforma Neopag ou de mensagem para o e-mail indicado no cadastro pessoal do Usuário." +
// ‍"10.2.O Usuário poderá, a qualquer momento, solicitar a exclusão da plataforma Neopag, encerrando seu relacionamento com a Neopag, mediante solicitação realizada diretamente por meio da plataforma ou outros canais de comunicação disponíveis.Neste caso, os dados do Usuário serão tratados de acordo com o disposto na Política de Privacidade." +
// ‍"11. MODIFICAÇÕES" +
    "11.1.A Neopag poderá, a qualquer tempo, alterar estes Termos de Uso ou a Política de Privacidade, a seu exclusivo critério.Quaisquer alterações nestes Termos de Uso e na Política de Privacidade serão informadas por meio da plataforma/aplicativo ou do site da Neopag; e com prazo de antecedência de 30 (trinta) dias da efetiva modificação." +
    "‍11.2.Será sempre indicada a data da última atualização realizada pela Neopag aos presentes Termos de Uso." +
    "‍11.3.O Usuário reconhece e aceita que, assim que publicada a alteração destes Termos de Uso e/ou da Política de Privacidade no site ou na plataforma/aplicativo, o uso dos mesmos passará a ser submetido aos Termos de Uso/Política de Privacidade atualizados." +
    "12. DISPOSIÇÕES GERAIS" +
    "12.1.Estes Termos de Uso não geram contrato de sociedade, franquia ou relação de trabalho entre o Usuário e a Neopag, seus profissionais, parceiros e/ou Anunciantes." +
    "‍12.2.Caso qualquer disposição destes Termos de Uso ou da Política de Privacidade venha a ser considerada ilegal, nula ou inexequível por qualquer razão, as disposições restantes não serão afetadas, permanecendo válidas e aplicáveis na máxima extensão possível." +
    "‍12.3.Estes Termos de Uso, a Política de Privacidade e o Contrato de Emissão e Utilização de Cartão Private Label Digital Neopag firmado com a loja conveniada constituem a totalidade do acordo sobre as condições de uso da plataforma Neopg.O Usuário declara ter ciência dos direitos e obrigações decorrentes dos presentes Termos de Uso e da Política de Privacidade, tendo lido, compreendido e aceito todos os termos e condições neles inseridos." +
    "13. LEI APLICÁVEL" +
    "Estes Termos de Uso será interpretado exclusivamente segundo as leis do Brasil.Apresentamos os Termos de Uso do domínio digital Neopag.Sugerimos, também, a leitura atenta de nossa Política de Privacidade, também disponível nessa mesma página." +
// ‍"Apresentamos os Termos de Uso da plataforma digital de private label – Neopag." +
    "Sugerimos, também, a leitura atenta de nossa Política de Privacidade, facilmente localizada através desse link: https://www.neopag.com/politica-de-privacidade. Para melhor organizar as informações, arrolamos, na sequência, os principais pontos deste Termo de Uso, mas destacamos ser muito importante a leitura da integralidade desse documento:" +
    "Todo o relacionamento e interação dos Usuários com a plataforma Neopag é realizada de forma digital e online." +
    "O Usuário não pagará qualquer tarifa pela a utilização da plataforma Neopag.Para utilizar a plataforma Neopag o Usuário baixa o aplicativo na loja virtual do seu smartphone, informa o número do seu CPF, e cria uma senha pessoal, sigilosa e intransferível.O Usuário não deve, em hipótese alguma, divulgar essa senha para terceiros e é o único responsável pelo uso não autorizado da senha cadastrada." +
    "O cadastro deverá ser efetivado completamente, facultando ao Usuário, ao depois do envio da documentação necessária, selecionar a loja conveniada de sua preferência e requerer crédito para a realização de suas compras, ocasião em que será digitalmente apresentado ao Usuário o Contrato de Emissão e Utilização de Cartão Private Label Digital Neopag a ser efetivado com a loja conveniada, definidor dos direitos, deveres e responsabilidades das partes negociantes.Requerido o crédito e aposto, ao depois da leitura integral, o aceite aos termos do Contrato de Emissão e Utilização de Cartão Private Label Digital Neopag (contratação “click-wrap”) com a loja conveniada, a equipe especializada da Neopag passará a analisar internamente os dados do Usuário, e, em tempo breve, acusará na própria plataforma/aplicativo do Usuário o avalor do crédito concedido, calculado através de critérios objetivos, incluindo consulta em órgãos de proteção ao crédito.A recusa na concessão do crédito após a verificação dos dados objetivos pesquisados não constitui qualquer medida discriminatória ou de índole pessoal, não implicando, por essa razão, em qualquer espécie de responsabilidade à Neopag.Como medida de maior segurança para o Usuário, além da senha pessoal a ser cadastrada, para a confirmação de todas as transações realizadas através da plataforma Neopag será gerado um token pelo sistema, a ser informado à loja para a efetivação da compra." +
    "Todas as informações dos Usuários são sigilosas e confidenciais, podendo ser utilizadas apenas e tão somente para a finalidade da plataforma Neopag, sendo autorizado, com a aceitação desses Termos, o acesso dessas informações pelas lojas conveniadas à plataforma Neopag.A utilização da plataforma Neopag é permitida apenas aos Usuários que possuem capacidade civil plena para a celebração de negócio jurídico, ou seja, maiores de 18 anos de idade.Ao utilizar a plataforma Neopag, o Usuário pode ter acesso também a serviços de terceiros.Nesse caso, os Usuários deverão analisar cuidadosamente os Termos de Uso desses terceiros.A Neopag não é responsável por esses serviços de terceiros." +
    "‍1.PRIMEIRAS INFORMAÇÕES" +
// ‍"Ficamos gratos por utilizar nossa plataforma de private label digital desenvolvida pela NEOPAG SERVIÇOS DE GESTÃO DE CRÉDITO E PARTICIPAÇÕES S.A., pessoa jurídica de direito privado, com sede na cidade de São Paulo/Capital, na Rua Maria Curupaiti, n0 441, sala 7001, Torre Design, Bairro Vila Ester, CEP 02452-001, inscrita no CNPJ sob o no 29.118.949/0001-72.Ao baixar nosso aplicativo e utilizar, de qualquer forma, nossos serviços, você estará concordando com esses Termos de Uso.Seu acordo conosco inclui esses Termos de Uso e nossa Política de Privacidade disponibilizada em https://www.neopag.com/politica-de-privacidade, sendo que ao utilizar nossos Serviços, você confirma que leu, compreendeu e está de acordo com os termos previstos, comprometendo-se a cumpri-los de forma integral.A aceitação desses Termos de Uso não supre, para a efetiva concessão de crédito e consumação de compra em crediário, a necessidade de firmar eletronicamente, o Contrato de Emissão e Utilização de Cartão Private Label Digital Neopag com a loja conveniada a que o Usuário requereu crédito, o qual será disponibilizado na plataforma Neopag para leitura e aceitação de forma simples e rápida Para fazer uso da plataforma Neopag o Usuário precisa, concomitantemente: (i) ter 18 (dezoito) anos de idade ou mais; (ii) ter um RG ou CNH em mãos; (iii) ter a capacidade de celebrar um contrato vinculativo e não ser impedido de fazê-lo segundo as leis aplicáveis; (iv) ser residente no Brasil, onde os Serviços estão disponíveis; e (v) ter um smartphone com sistema operacional IOS ou Android, nas versões mínimas, com câmera frontal e com acesso à internet banda larga (3G ou 4G). O Usuário também confirma que quaisquer informações de cadastro enviadas são verdadeiras, precisas e completas, tendo ciência que qualquer incompatibilidade apurada ocasionará a impossibilidade de uso da plataforma/aplicativo, sem qualquer responsabilidade da Neopag." +
    "2. DEFINICÕES" +
// ‍"Para os fins destes Termos e Condições de Uso, as designações abaixo terão  os seguintes significados: Usuário(s): a pessoa física, maior de idade, ou jurídica, por intermédio de representante legal devidamente habilitado, com plena capacidade de contratar, que acessa a plataforma Neopag e realiza o seu cadastro pessoal de modo a usufruir das funcionalidades oferecidas pela plataforma/aplicativo Neopag, aceitando, nessa oportunidade, incondicionalmente, os presentes Termos de Uso e a Política de Privacidade.Plataforma ou Plataforma/Aplicativo Neopag: o aplicativo da Neopag desenvolvido para operação em smartphone que tenha o sistema operacional IOS ou Android, nas versões mínimas, com camera frontal e com acesso à internet banda larga (3G ou 4G).Neopag: é a sociedade empresária NEOPAG SERVIÇOS DE GESTÃO DE CRÉDITO E PARTICIPAÇÕES S.A., pessoa jurídica de direito privado, com sede na cidade de São Paulo/Capital, na Rua Maria Curupaiti, n0 441, sala 7001, Torre Design, Bairro Vila Ester, CEP 02452-001, inscrita no CNPJ sob o no 29.118.949/0001-72.Loja Conveniada: Comércio varejista que aderiu ao sistema Neopag de gerenciamento de seu crédito e por essa razão realiza vendas no crediário através da plataforma Neopag, relação essa regida por contrato específico firmado entre a loja e a Neopag.Dados Pessoais: significa todo e qualquer dado disponibilizado pelo Usuário que, de alguma forma, o identifique, como, exemplificativamente, nome, endereço, CPF, número de telefone, endereço de e-mail, ou quaisquer outras informações.Serviço(s): Todos os serviços postos à disposição do Usuário na plataforma Neopag.SAC: Serviço de atendimento ao Usuário/Cliente da plataforma Neopag, que poderá ser consultado através do e-mail: meajuda @neopag.com.Termos de Uso: Os presentes Termos aplicáveis a todas as compras feitas através da plataforma private label digital Neopag.Política de Privacidade: significa a política de privacidade que disciplina a utilização dos dados do Usuário, que pode ser encontrada no seguinte link: https://www.neopag.com/politica-de-privacidade.Aceitar ou Aceite: o ato de o Usuário clicar na caixa “Li e aceito os Termos de Uso e Política de Privacidade”, bem assim, na caixa “Li e aceito os termos do Contrato de Emissão e Utilização de Cartão Private Label Digital Neopag” dispostas na plataforma/aplicativo Neopag. Tal ato implica consentimento prévio, expresso e informado do Usuário em relação a todo o disposto em tais documentos, autorizando o armazenamento de base de dados composta por Dados Pessoais, entre outras informações." +
// ‍"3. ENTENDENDO A PLATAFORMA NEOPAG – VEJA OS BENEFÍCIOS!" +
    "Neopag é a primeira plataforma gestão de crédito e fidelização de clientes do Brasil.Ela permite que lojistas ofereçam seu próprio CARTÃO DIGITAL apoiado por um conjunto de ferramentas para gestão de risco, crédito, relacionamento e cobrança.Neopag é vender mais, com seguraça e tranquilidade.Quais vantagens, como consumidor (Usuário), eu tenho com Neopag?Neopag ajuda você conseguir crédito para comprar nas suas lojas preferidas.Com o aplicativo Neopag voce controla todos os CARTÕES DIGITAIS, organiza suas compras, controla suas faturas e usando o aplicativo você ganha pontos pra conseguir descontos, promoções exclusivas e mais crédito para continuar comprando.Como funciona?Primeiro você precisa baixar o aplicativo e se cadastrar.Fique tranquilo, o processo é 100% seguro e sigiloso.Após o cadastro você terá acesso à lista de lojas da sua região que usam Neopag.Encontrando a sua loja preferida basta conectar com ela.Como consigo crédio?Quando você se conecta com uma loja, acontece um processo de avaliação de crédito que vai definir o quanto você conseguirá comprar na loja.Você conseguirá ver tudo no aplicativo.Não se preocupe se não conseguir crédito, a Neopag ajuda você a completar informações para ganhar mais pontos.Posso comprar em qualquer loja?A Neopag fortalece o vinculo entre lojistas e seus clientes, além de construir uma rede de confiança para conectar novos lojistas e novos clientes para fortalecer a economia local.Desta forma todas as lojas credenciadas na plataforma Neopag estarão disponiveis para que você se conecte e eventualmente consiga crédito para compras.Como faço para comprar?Basta ir até qualquer loja da rede Neopag e informar que quer comprar com Neopag.O processo é bem simples, você escolhe seus produtos e no momento de pagar você informa quantas vezes quer parcelar suas compras e confirma a compra.Como faço para pagar?Você poderá acompanhar as faturas e os valores a pagar em cada uma das lojas.O pagamento é feito diretamente na loja ou outra forma de pagamento que ela disponibilizar." +
// ‍"4. ADESÃO, CIÊNCIA DO NEGÓCIO JURÍDICO REALIZADO E CONSEQUÊNCIAS DO INADIMPLEMENTO" +
// ‍"Para obtenção da totalidade dos benefícios proporcionados pela plataforma Neopag, o Usuário deverá efetuar o seu cadastro na plataforma/aplicativo Neopag, fornecendo seus Dados Pessoais.Para a realização do cadastro, é obrigatória a leitura, compreensão e Aceite dos presentes Termos de Uso e da Política de Privacidade pelo Usuário.Para a obtenção de crédito para utilização na loja conveniada o Usuário deverá ler e aceitar os termos do Contrato de Emissão e Utilização de Cartão Private Label Digital Neopag firmado com o comerciante.O ACEITE DOS TERMOS DE USO, DA POLÍTICA DE PRIVACIDADE E DO CONTRATO DE EMISSÃO E UTILIZAÇÃO DE CARTÃO PRIVATE LABEL DIGITAL NEOPAG IRÁ IMPLICAR O RECONHECIMENTO, PELO USUÁRIO, DE QUE ELE LEU, ENTENDEU E ACEITOU INCONDICIONALMENTE TODAS AS DISPOSIÇÕES CONSTANTES DESSES DOCUMENTOS, ADMITINDO QUE AS COMPRAS REALIZADAS ATRAVÉS DA PLATAFORMA NEOPAG SÃO DE SUA RESPONSABILIDADE, ESTANDO SUJEITO AOS MEIOS DE CONBRANÇA EXTRAJUDICIAIS E JUDICIAIS EM CASO DE INADIMPLEMENTO." +
// ‍"5. DA UTILIZAÇÃO DA PLATAFORMA NEOPAG" +
    "5.1.A Neopag, por meio deste Termos de Uso, concede ao Usuário uma licença pessoal, limitada, temporária, mundial, revogável, não exclusiva e intransferível de uso da plataforma/aplicativo, sem cobrança de remuneração do Usuário de qualquer natureza, sendo certo que o Usuário não poderá utilizar e nem permitir o uso da plataforma para qualquer outra finalidade não expressamente prevista neste Termos de Uso.Desta forma, não será permitido ao Usuário, sem qualquer limitação, copiar, modificar, distribuir, vender, alugar, compartilhar ou, ainda, ceder, a qualquer título, os serviços disponibilizados pela Neopag." +
// ‍"5.2.No ato de seu cadastro na plataforma Neopag, o Usuário fornecerá à Neopag seus Dados Pessoais, criando uma senha confidencial e de responsabilidade exclusiva do Usuário." +
// ‍"5.2.1.O Usuário será responsável pela veracidade, validade e precisão dos Dados Pessoais por ele fornecidos no seu cadastro, competindo-lhe manter referido cadastro sempre atualizado." +
// ‍"5.2.2.A Neopag não terá obrigação de policiar ou fiscalizar os Dados Pessoais fornecidos pelos Usuários, mas poderá, a seu exclusivo critério, excluir as informações que lhe pareçam inverídicas ou excessivas." +
// ‍"5.3.A utilização da plataforma pelo Usuário possui caráter pessoal e intransferível e está autorizada unicamente para fins lícitos relacionados ao propósito a que a plataforma/aplicativo se destina, de acordo com estes Termos de Uso.A propriedade intelectual da plataforma pertence, e continuará pertencendo, exclusivamente à Neopag." +
// ‍"6. DA COMUNICAÇÃO COM A NEOPAG" +
// ‍"Para qualquer assunto relacionado às condições destes Termos de Uso ou da Política de Privacidade, bem como ao Contrato de Emissão e Utilização de Cartão Private Label Digital Neopag e à plataforma/aplicativo, o Usuário deverá entrar em contato com a Neopag mediante mensagem endereçada ao e- mail meajuda @neopag.com ou através do watts up pelo n.11 94058-4887." +
    "7. PROPRIEDADE INTELECTUAL" +
    "7.1.O Usuário não adquire, por meio do presente Termos de Uso ou da Política de Privacidade, nenhum direito de propriedade intelectual ou outros direitos exclusivos, incluindo patentes, desenhos, marcas, direitos autorais ou direitos sobre informações confidenciais ou segredos de negócio, sobre ou relacionados ao Aplicativo, bem como à base de dados composta por dados de Usuários, os quais são de propriedade exclusiva da Neopag." +
// ‍"7.2.Todo e qualquer conteúdo disponibilizado na plataforma/aplicativo, bem como toda e qualquer base de dados constituída pela Neopag pertencem exclusivamente à Neopag e são protegidos pela lei brasileira, especialmente no que se refere à propriedade intelectual e aos direitos autorais.Na qualidade de exclusivo titular da propriedade intelectual da citada base de dados, a Neopag poderá utilizá-la livremente e da forma que melhor atenda seus interesses." +
// ‍"7.3.A Neopag poderá, a seu exclusivo critério, a qualquer tempo e sem necessidade de comunicação prévia ao Usuário: (i) encerrar, modificar ou suspender, total ou parcialmente, o acesso do Usuário à plataforma/aplicativo, quando referido acesso ou cadastro violar as condições estabelecidas nestes Termos de Uso e/ou na Política de Privacidade; (ii) excluir, total ou parcialmente, as informações cadastradas pelo Usuário que não estejam em consonância com as disposições destes Termos de Uso;" +
// ‍"7.4.Poderá, ainda, a Neopag, a seu exclusivo critério, suspender, modificar ou encerrar as atividades da plataforma, mediante comunicação prévia ao Usuário, salvo nas hipóteses de ato de autoridade competente, caso fortuito ou força maior." +
// ‍"7.5.A Neopag poderá, a qualquer tempo, mediante comunicação prévia ao Usuário no endereço de e-mail por este indicado em seu cadastro pessoal e por meio de aviso na própria plataforma Neopag, definir preços para oferecimento de determinados Conteúdos e/ou Serviços, ainda que inicialmente tenham sido ofertados de forma gratuita e deverá, ainda, de forma clara, indicar qual o preço vigente de determinado serviço, questionando o Usuário sobre a sua vontade de prosseguir com referida contratação." +
// ‍"7.6.O Usuário AUTORIZA, neste ato, a Neopag a enviar para o seu endereço de e-mail mensagens ou outras correspondências de caráter informativo, comercial e/ou promocional." +
    "8. INFORMAÇÕES CONFIDENCIAIS E POLÍTICA DE PRIVACIDADE" +
    "8.1.Ao cadastrar-se na plataforma Neopag, o Usuário concorda com a Política de Privacidade: https://www.neopag.com/politica-de-privacidade. Mediante Aceite da Política de Privacidade, o Usuário concede à Neopag AUTORIZAÇÃO para uso dos seus dados, de acordo com as regras constantes destes Termos de Uso e da Política de Privacidade." +
    "8.2.Ao emitir o seu “de acordo” no momento do cadastro, o Usuário autoriza que a Neopag divulgue, compartilhe e troque as suas informações com qualquer outro terceiro, para fins de registro, análise de risco de crédito e qualquer outra finalidade." +
    "8.3.O Usuário autoriza a Neopag a verificar os dados fornecidos no cadastro e a obter e fornecer tais informações às empresas de análises de crédito e de proteção ao crédito e ao Sistema de Informações de Crédito (“SCR”) do Banco Central do Brasil, inclusive informações decorrentes de operações de crédito de sua responsabilidade, para fins de avaliação do risco de crédito e intercâmbio de informações com outras instituições financeiras.O Usuário declara estar ciente de que a consulta ao SCR depende dessa prévia autorização e que o Usuário pode ter acesso aos dados do SCR pelos meios colocados à sua disposição pelo Banco Central do Brasil.Em caso de divergência nos dados do SCR fornecidos pela Neopag, o Usuário poderá solicitar correção, exclusão ou registro de anotação complementar, mediante solicitação formal.O Usuário declara estar ciente de que, ocorrendo a falta de pagamento de qualquer obrigação assumida e não sendo solucionada a pendência pela via extrajudicial, será promovida demanda judicial competente." +
    "9. INDENIZAÇÃO" +
    "9.1.O Usuário concorda em defender, indenizar e manter indene a Neopag, diretores, empregados e agentes, de e contra quaisquer encargos, ações ou demandas, incluindo, exemplificativamente, honorários advocatícios razoáveis, resultantes: (i) da eventual utilização indevida da plataforma Neopag; (ii) da violação das condições ora pactuadas; (iii) qualquer atividade da qual o Usuário participe ou por meio dos Serviços; e (iv) a violação de qualquer lei ou dos direitos de terceiro." +
    "‍9.2.Em nenhum caso a Neopag será responsável por danos pessoais ou qualquer prejuízo incidental, direto, indireto ou consequente, lucros cessantes, incluindo, sem limitação, prejuízos por lucros cessantes, corrupção ou perda de dados, falha de transmissão ou recepção de dados, não continuidade do negócio ou qualquer outro prejuízo ou perda comercial, decorrentes ou relacionados à prestação de serviços por terceiros." +
    "10. VIGÊNCIA E RESCISÃO" +
    "10.1.Estes Termos de Uso e a Política de Privacidade vigerão por prazo indeterminado, a partir do Aceite do Usuário, podendo ser modificados ou rescindidos unilateralmente por qualquer das partes a qualquer tempo, sem qualquer ônus, mediante simples comunicação por meio da própria plataforma Neopag ou de mensagem para o e-mail indicado no cadastro pessoal do Usuário." +
    "‍10.2.O Usuário poderá, a qualquer momento, solicitar a exclusão da plataforma Neopag, encerrando seu relacionamento com a Neopag, mediante solicitação realizada diretamente por meio da plataforma ou outros canais de comunicação disponíveis.Neste caso, os dados do Usuário serão tratados de acordo com o disposto na Política de Privacidade." +
    "‍11. MODIFICAÇÕES" +
    "11.1.A Neopag poderá, a qualquer tempo, alterar estes Termos de Uso ou a Política de Privacidade, a seu exclusivo critério.Quaisquer alterações nestes Termos de Uso e na Política de Privacidade serão informadas por meio da plataforma/aplicativo ou do site da Neopag; e com prazo de antecedência de 30 (trinta) dias da efetiva modificação." +
    "‍11.2.Será sempre indicada a data da última atualização realizada pela Neopag aos presentes Termos de Uso." +
    "‍11.3.O Usuário reconhece e aceita que, assim que publicada a alteração destes Termos de Uso e/ou da Política de Privacidade no site ou na plataforma/aplicativo, o uso dos mesmos passará a ser submetido aos Termos de Uso/Política de Privacidade atualizados." +
    "‍12. DISPOSIÇÕES GERAIS" +
    "12.1.Estes Termos de Uso não geram contrato de sociedade, franquia ou relação de trabalho entre o Usuário e a Neopag, seus profissionais, parceiros e/ou Anunciantes." +
    "‍12.2.Caso qualquer disposição destes Termos de Uso ou da Política de Privacidade venha a ser considerada ilegal, nula ou inexequível por qualquer razão, as disposições restantes não serão afetadas, permanecendo válidas e aplicáveis na máxima extensão possível." +
    "‍12.3.Estes Termos de Uso, a Política de Privacidade e o Contrato de Emissão e Utilização de Cartão Private Label Digital Neopag firmado com a loja conveniada constituem a totalidade do acordo sobre as condições de uso da plataforma Neopg.O Usuário declara ter ciência dos direitos e obrigações decorrentes dos presentes Termos de Uso e da Política de Privacidade, tendo lido, compreendido e aceito todos os termos e condições neles inseridos." +
    "13. LEI APLICÁVEL" +
    "Estes Termos de Uso será interpretado exclusivamente segundo as leis do Brasil.";
export default text;
