export default perfilStyle = {
    content: { width: "100%", height: "100%", alignItems: "center" },
    bgView: { width: '100%', height: "40%" },
    bgImage: { height: "100%", width: "100%", alignItems: 'center', justifyContent: "center" },
    configButton: { width: "100%", height: 30, alignItems: "flex-end" },
    profilePic: { height: 150, width: 150, borderRadius: 100, opacity: 2, borderColor: "#fff", borderWidth: 3 },
    userName: { fontSize: 22, fontWeight: "bold", marginTop: 10 },
    contentData: { width: "100%", height: "15%", padding: 10, flexDirection: 'row', justifyContent: "center" },
    contentViewLeft: { alignItems: "center", justifyContent: "center", width: "100%" },
    contentViewRight: { alignItems: "center", justifyContent: "center", width: "100%" },
    dividerProps: { color: "#CDCDCD", insetType: "center", width: 2, orientation: "horizontal" },
    scroll: { width: "100%", height: "55%" },
    viewData: { width: "100%", flexDirection: 'row', alignItems: "center", padding: 15 },
    textData: { fontWeight: 'bold', fontSize: 20 },
    avatarProps: { size: 50, color: "#CDCDCD" },
    avatarStyle: { backgroundColor: '#fff' },
    dividerDataProps: { color: "#CDCDCD", insetType: "center", width: 1, orientation: "horizontal" },

    plansTextClose: { fontSize: 14, fontWeight: 'bold' },
    plansContainer: { width: "100%", height: "90%", alignItems: 'center', justifyContent: "center" },
    plansContent: { flexDirection: 'row', justifyContent: "space-between", width: "100%", flexWrap: 'wrap' },
    plansViews: { width: "50%", flexDirection: 'row', alignItems: "center", padding: 15 },
    plansButton: { width: "80%", borderRadius: 15, marginBottom: 15 },
    plansButtonProps: { icon: "send", mode: "contained", color: "purple" },
    plansContentView: { alignItems: "center" },
    plansContentText: { fontWeight: 'bold' },
    plansAvatarBg: { backgroundColor: '#fff' },

    helperProps: { type: "error", theme: { mode: "adaptive" } },
    helperPass: { fontWeight: 'bold', fontSize: 12, marginBottom: 8 },
    helperPassProps: { type: "error", theme: { mode: "adaptive" } },
    helperText: { fontWeight: 'bold', fontSize: 12 },

}